[package]
name = "informant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "informant"

[dependencies]
ggez = {git = "https://github.com/Cosmic-Goat/ggez"} # "0.7"
# winit = "0.24.0"
glam = { version = "0.20.5", features = ["mint"] }
keyframe = "1.0.4"
fontconfig = "0.5.0"
