[package]
name = "logout-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "logout-rs"

[dependencies]
piston = "0.53.0"
piston2d-graphics = "0.42.0"
# pistoncore-glfw_window = {path = "../glfw_window"} #"0.75.0"
pistoncore-glutin_window = {path = "../glutin_window"} #"0.69.0"
winit = "0.24.0"
piston2d-opengl_graphics = "0.81.0"
