# This config file shows the available options for informant, as the default
# values (which will be used if any options are omitted from the config file).
#
# Only options that are marked as required are actually required in order to run
# the program without error.

[window]
# Window mode. Options are "Windowed", "Borderless", and "Full". Different WMs
# have different behaviors, you'll have to try these out for yourself. For
# example, on i3wm "Full" will not show programs behind a transparent window.
mode = "Borderless"

# The size of the window. Only has an effect in Windowed mode. If not provided,
# it will default to your WM's behaviour.
size = [800, 600]

# The position of the window. Only has an effect in Windowed mode. If not
# provided, it will default to your WM's behaviour.
position = [0, 0]

# The title of the window. Use this to set different window rules from your WM
# for each config (for example, if you wanted one config to be tiled, and
# another to be floating).
title = "Informant"

# Whether the window should be always on top.
always_on_top = true

# Whether the window should be transparent. Note you will also need to make your HTML
# transparent for this to be effective. For example:
# <body style="background-color: rgba(0,0,0,0.3)"> ... </body>
transparent = true

