# This config file shows the availble options for informant,
# as well most of the default values used if not provided via config.
#
# Only options that are marked as required are actually required
# in order to run the program without error.

[window]
# Window mode. Options are "Windowed", "Borderless", and "Full".
# Different WMs have different behaviours, you'll have to try these out for
# yourself. For example, on i3wm "Full" will not show programs behind a
# transparent window.
mode = "Borderless"
# The size of the window. Only has an effect in Windowed mode.
# If not provided, it will default to your WM's behaviour.
# size = [800, 600]
# The position of the window. Only has an effect in Windowed mode.
# If not provided, it will default to your WM's behaviour.
# position = [0, 0]
always_on_top = true
transparent = true

# Hotkey shortcuts are also specified via an array, as shown here.
# You can add or remove as many as you want.
[[keymap]]
# The key to bind the command to. REQUIRED.
key = "L"
# mods = ["SHIFT", "CTRL"]
# The command to run when the shortcut is detected. REQUIRED
command = "echo test"
