# This config file shows the availble options for informant,
# as well as their default values used if not provided via config.
#
# Only options that are marked as required are actually required
# in order to run the program without error.

[window]
fullscreen = "Windowed"

# Hotkey shortcuts are also specified via an array, as shown here.
# You can add or remove as many as you want.
[[keymap]]
# The key to bind the command to. REQUIRED.
key = "L"
# mods = ["SHIFT", "CTRL"]
# The command to run when the shortcut is detected. REQUIRED
command = "echo test"
