fullscreen = false
background = [0.1, 0.1, 0.1, 0.7]

[[buttons]]
label = "Sleep"
command = "test"
# thickness = 1.0

[[buttons]]
label = "Poweroff"
command = "test"
thickness = 1.0

[[buttons]]
label = "Reboot"
command = "test"
thickness = 1.0

[[keymap]]
key = "L"
# mods = ["SHIFT", "CTRL"]
command = "echo test"

[anim]
duration = 1.5
delay = 0.5

[font]
family = "sans"
style = "thin"
size = 24.0

[line]
thickness = 1.5
